name: Suggestion
description: Here's something you can add to the website.
title: "[SUGGEST] "
labels:
  - "suggestion"
body:
  - type: checkboxes
    attributes:
      label: Have you read the [contributing guidelines](./.github/CONTRIBUTING.md)?
      description: Please read the contributing guidelines before contributing.
      options:
        - label: I have read the contributing guidelines.
          required: true

  - type: textarea
    attributes:
      label: What is your suggestion?
      description: Give as much detail as you can.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Would you like to work on this?
      options:
        - label: I would like to work on this.
          required: false
